### ISSUE TITLE
Simplify CircleCI Setup

### ISSUE THREAD

**Issue by bernerdschaefer** [thoughtbot/go-template#7]
The CircleCI setup is way more complex than I'd like.

It ended up that way, because we wanted to ensure that we only installed dependencies that were vendored. It was also designed for Go 1.4.

Unfortunately, CircleCI does not yet support Go 1.6, which has full support for `vendor/`, but we should still be able to clean up the `circle.yml` for laces projects. We recently used this on another project -- perhaps it would work for the general case as well?

``` yml
machine:
  environment:
    GO15VENDOREXPERIMENT: "1"

dependencies:
  override:
    - bin/setup

test:
  pre:
    - bin/vet

  override:
    - go test ./...
```
